language: java

jdk: oraclejdk8

before_script:
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then export DATABASE_RELEASE_URL="$DATABASE_STAGING_URL"; fi
  - if [ "$TRAVIS_BRANCH" == "master" ];  then export DATABASE_RELEASE_URL="$DATABASE_PRODUCTION_URL"; fi

script:
  - mvn clean install -PdbRecreate

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then chmod 755 ./update-gh-pages.sh; ./update-gh-pages.sh; fi
after_deploy:
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then chmod 755 ./trigger-rainbow.sh; ./trigger-rainbow.sh; fi

cache:
  directories:
  - $HOME/.m2

# The following global varables are encrypted:
env:
  global:
  # GH_TOKEN
  - secure: AanbVsRGmMQnNolKxIL9p2zHLo59fXcrmRhZG+T1neTBJjlclQSwfwcdNTooNZQaxuJlTaRxWi7J8eTKQnpdjMnun9o1l9K/1NLOxBjlR7/9579p4tV4SLfKcR4OWUDJAs1vv8pXd9CmQpp8ihekXL9yR4Fo8pTbwj6CjnI9J9/5bFrBecU2oxm309qTzGaSofjiO9qEtzNW47ZDtexrpF8DM44rCo05OdysoPav1pVh2s/j9xMXWGKDO8RxkPSTr70rtX7W2OR6JZkz1PaEWrCj1n8SVVoe/Qn946y784BQ7WdlBZDDvwFezqBrLiXhAuuWh0GUI+varRn6MuRbUeujiMhgKkYWPI7GWyPLcgk7xy5hNU3yAy7UTDdnyrXw63l+ClfMuW4TzYU36Mz3DaVVxrNTjX35OBM0j1ZzFTeDJzt3AyfTgicw11IAIi5C/9T1PY4MjShvgC15UDmdZmtHLwJf6Q6OQot4/AcNZffW+/FjDxZ3kap7x1pZe+WhUVvALwEdd5FKLmeql8vydtWeuZKEQromqPR2Y8XcV7fYg4Q+1qwos+pfL9YKDOqamZXu/YIMmiduxFrQMiQhGx2qQFM2AP06QSEc94zhPrEoFoeqetMCSqRm4VEF3R23QGOE2V3H6NZEWgdFRuJduDGNpQvaghxQMYVLIyk1RuI=
  # ACCESS_TOKEN
  - secure: jdRYR3VUlWR8yxC+BQQsrL3E5myGnL4CxTuBEz26taAhcdJGvQoFvutb+LCH0r0WNZ9Ca0DCc32+ocCyTPuArHAanCiNZl8C5MoeC2pMJZbwQeHIAUy+kJJ7TScardKh/FPMRL01O2PxGAh3gm9zCeUglfaQdZfCLU5qDxQxU2iQ49PexWP3sNAUBhN+U+03WWUn4OQorIZQWzGbUv1UYBXguzv6EbXR+iIVZ9Bq6JWo0P0/u+Fp87p4RxhohBrpDEuDhkBb9s77KLO3A7FB/5Cq6du2WlqUSI+ivS9oU9jCqZjZgQPjdQwEP2d+325ESLOMRl6X6lyTeQRZfpkf65m7FEG1g7iIG/v344I01DqF9hgT6hhNSbklS535IITySMeKU/RR6otanSdXWUNK1IowNLkg++gj/8XW3z8JwfTpOqP2WY7CYezomYxLz1C2LkEevH6SMY23vEJRnR3fTmKJWJcujWcq6ZAEO2ja8Lg4VAwKBPijQ3t8QBoywgnmJte9lS5xw881dfkCRuBX8q16dsPBV9I0xyRtREzr0vtTPTPoXJRCaXTRVwaAnpq9L0idNfVpsbitvGmB17NnO0pWzUpuk5jpVMdDGMvXXa+ixbFZr1ivnIq5y0YBaIwKO9jsPAm6aREUpL5ZsOooekTpiXVbs2he18voiqqIAh8=
  # DATABASE_URL
  - secure: bFgK63DoYGifwyv9IK4xAHYx8qkmcvnOU/DpmdhYufH5PB/2Fqpb8xbfb+AFiWGGzqDxC/iLyZg4zdsNlTZtXk7DKcC9PQBAjoJteSDFtco+jrgHt73IJxn8l/LM4MKUYf4AqGIcyVRPTeCeiDtdk+Qp2r2oQ83r+kIpzzboQqMtyfX+5R2NAwsDSDkfNVYqfOBA4vqOvZlblFTJpd8TCwBMKbEWruSxXMCZHXzUGX5zl+EpcU7pQs6+dCUjhO+tTWxv03NlZqDcQN672ZguH2NkbTPhIrZ4l99z4txfjTusIzvOC/bt6iwjgeHqaztQ2uVgnnxMXNFxiVV7/RtRL1f93UOeYy3tHg6mXSx9UHNbBx6evOsiEwtFYhJL+mRU/cvX8k2iNFG6nTGgvdoiVcsVkNvduDqGHK3MG+viaqJ6KD47Y4tYfWq6Yq9TVa0wrvYL6Ey/YVnV6VH7AApnXKhIBeLrhdTIFXTNwM533H8VL+y/wLVhx/Wi4q+VKMXy9AZ2JMvebSoDaUutdanx+qOFYsLOKZMDxWQmKSsAXM4rl0VE1eUd+3FfBMl7UW1zhz+B0yxwOu9Tm5+KQhqwsY8SxjCZNG2SRGF13gYCCRSvBgy0SB1bpBe4FWrb6d3VCSTDpzLZj/P4d2pDR1u31ZjyQ3jPtTrF8fYJqnT3r6E=
  # DATABASE_STAGING_URL
  - secure: jJlDryHqJ59L4Na94hBadLfBFGtNOOnq90PmNEZ3HJpiyiJZpg3BkNHzGiIZlyK/QdfnlMka77R8Z3FRd55ZLwXqUCfdyWoBhY5WykwZh9jpoD7fBaVtL8f7p5HmMz654IwjbRudkoroBRsDv4cd1q7pIeCFx7NLwHH7E5xzpc/kgOu2TWjZItJ3i39zLqKkTFtw4owA2BT+aSdmh/dxme8klwrF6y0iieaQ+a6ZqomnlV30JwOIDPcoV17db5XvvStouv7L2D+s6+nDK3NL1zm5f3CbKbMgArv0jRMahnNOyJHbAAYFHL+o5ef8Z+B1Rgtk4XSJYqsiI0EwrfTmCarDLiSFp8OuvipXuwJxra67mkQmWpgLLD39FWAaofkMhY7wuLEfpx7LYY4X0UyGjRwFAj/JL3I4x+3sN9um6S0F/8pvZaHVoiFkiaMf7ZQGGbZNKcVrRX01quDa4YFJEYWJlsWiyUAaJrxmYhKFsFLqtunnhULFQaUf6GCMyxFzqsijy4xFATcXShR/PBTVXjCPkhUNMMqYudvZLCJ7caDkTLoq2Zaq0PuvXlpMtSX5yiwvVtmJdvUe6paIMLXmCmrA9fId0xqRux15rCuvcQjs3HpCS1AdnZn69dWtPIc0h+jQp8Oqy0s9vL8rBoN27QIDa58mlpZ3q9oyIiPPO0Y=
  # DATABASE_PRODUCTION_URL
  - secure: Md5O3nY/Q3KDi1aRy1nEr4P+dMoHzAf1QSBDaVKB/AClVKuMAWK2r6BT+57vTWS7x7bvznT0z+0leYUOkZWQ/MyHymRHplW/qYPB5NpyNc1e4DPYCgHzIbjEn6qpreCiqeDDFu+N3/J+wsXXNf130OLI8EgRfHBTMc2cv/kYbW+4gU/FD3DcyfcmuvxT/WomyA8yCqhCP/YN6B8aWUZXLCbxXb2nGoK3/NiKgzvbct9onOVDNOqEDB1maJHohCBtCqZmNn3dXtlqtmwb5atD9H7O0mf/o4GOKB/zmpF1UYOc3X1gYg5IMx5tq4cv27MObX7EnMQW9BLVESUfVbEicmlHLIOgVXjZxMFKCjRV6P47ewvYrnwwV/qSFmypcQP1DmTK6/f542vcfNanonirIJn+L+5HjT25VymoUNYCgGzWqoBir4Oeo5j5gkoZP9OqFrLAtLuLJL7TqzuGaPLwdOvEYGznh13w60hkh9AgXpGkK1Xf43dEEqzPTL1hXEw6Hrh2e6nFl9czV7EWmrSgDI5rBTCxLrnyuBoCYrtQXMl3g87xZw1+zVw5H6PGfi742T2Y4QzvH6kmEzZmiHK7nLdLmyaYdouOv9XtDgPUdJeA993KY0e9obAjviI45jSNJsN7QUGJJ1uXN448roOS7fzB0nVeZCZCVtK8RZSj/4I=

deploy:
  provider: heroku
  api_key:
    secure: zxS4+O/SeOogoW1qQpUHAuAE+Wb1ZHznyHeYn0vqvj0CUYsw/y4jKw+beGU51WmYjHRrQpFU+/+MghMcPotzfBMzwX9ASjQ/I64T4yGrrUcoiM/AjKnti8OfBZQbP1bN5R8CcNKMYpnqqRu5P490LEOPz2QTAiCPQJexss9Hkzb60x6n4IXFjxhTsmuPy5J6DG2L1llcxLF//KIeNssi6mFHIyPRAzswjNMpZgr5bQsAZIX3M9MOHczX+PjNtsFz7iCQnp+NCwz5HQpzCeww6G7B2zmCwqFyHyJKuH9JSwTqGC4z5jsHA3Z/mbJhU+hLYi1VLHNi+ZhW80cF94s8amJDRm/+9FfQUwT5YmOLRCWhdFA8FrQnQLi9nJ16ZFu5MuM+mMCrvcjcxkAoKOQauHMdAw8ZcNiUrg1Go+y2j79Moau43OAWxBF1z8uoSe2NZizF4wVN4IUv1sSReEI48fN3iDzyZm8gkUnhzSuG1lESjvsQbPl6cKF8W2otl3EGHtKpJzlwxwyzIMF3QpIbgHQXO7cFTYVSykCbLkkXXdW0ZOFU/4NY0ls4TWuQ/45VkCIuX9m9exJgLJJqAgveW8LvIP8hxKgXcqWg6/Vao0xAoYzOnVgQe6DgtmOQ3e64nfpmZ67AwYQEZqtxYiXa03j9YXnqJUf7wcawzWkNtQM=
  app:
    master: frozen-mountain-3180
    staging: sheltered-river-1312
