language: java

jdk: oraclejdk8

before_script:
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then export DATABASE_RELEASE_URL="$DATABASE_STAGING_URL"; fi
  - if [ "$TRAVIS_BRANCH" == "master" ];  then export DATABASE_RELEASE_URL="$DATABASE_PRODUCTION_URL"; fi

script:
  - mvn install -PdbMigrate

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then chmod 755 ./update-gh-pages.sh; ./update-gh-pages.sh; fi
after_deploy:
  - chmod 755 ./update-build-number.sh; ./update-build-number.sh
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then chmod 755 ./trigger-rainbow.sh; ./trigger-rainbow.sh; fi

cache:
  directories:
  - $HOME/.m2

# The following global variables are encrypted:
env:
  global:
  # GH_TOKEN
  - secure: AanbVsRGmMQnNolKxIL9p2zHLo59fXcrmRhZG+T1neTBJjlclQSwfwcdNTooNZQaxuJlTaRxWi7J8eTKQnpdjMnun9o1l9K/1NLOxBjlR7/9579p4tV4SLfKcR4OWUDJAs1vv8pXd9CmQpp8ihekXL9yR4Fo8pTbwj6CjnI9J9/5bFrBecU2oxm309qTzGaSofjiO9qEtzNW47ZDtexrpF8DM44rCo05OdysoPav1pVh2s/j9xMXWGKDO8RxkPSTr70rtX7W2OR6JZkz1PaEWrCj1n8SVVoe/Qn946y784BQ7WdlBZDDvwFezqBrLiXhAuuWh0GUI+varRn6MuRbUeujiMhgKkYWPI7GWyPLcgk7xy5hNU3yAy7UTDdnyrXw63l+ClfMuW4TzYU36Mz3DaVVxrNTjX35OBM0j1ZzFTeDJzt3AyfTgicw11IAIi5C/9T1PY4MjShvgC15UDmdZmtHLwJf6Q6OQot4/AcNZffW+/FjDxZ3kap7x1pZe+WhUVvALwEdd5FKLmeql8vydtWeuZKEQromqPR2Y8XcV7fYg4Q+1qwos+pfL9YKDOqamZXu/YIMmiduxFrQMiQhGx2qQFM2AP06QSEc94zhPrEoFoeqetMCSqRm4VEF3R23QGOE2V3H6NZEWgdFRuJduDGNpQvaghxQMYVLIyk1RuI=
  # ACCESS_TOKEN
  - secure: jdRYR3VUlWR8yxC+BQQsrL3E5myGnL4CxTuBEz26taAhcdJGvQoFvutb+LCH0r0WNZ9Ca0DCc32+ocCyTPuArHAanCiNZl8C5MoeC2pMJZbwQeHIAUy+kJJ7TScardKh/FPMRL01O2PxGAh3gm9zCeUglfaQdZfCLU5qDxQxU2iQ49PexWP3sNAUBhN+U+03WWUn4OQorIZQWzGbUv1UYBXguzv6EbXR+iIVZ9Bq6JWo0P0/u+Fp87p4RxhohBrpDEuDhkBb9s77KLO3A7FB/5Cq6du2WlqUSI+ivS9oU9jCqZjZgQPjdQwEP2d+325ESLOMRl6X6lyTeQRZfpkf65m7FEG1g7iIG/v344I01DqF9hgT6hhNSbklS535IITySMeKU/RR6otanSdXWUNK1IowNLkg++gj/8XW3z8JwfTpOqP2WY7CYezomYxLz1C2LkEevH6SMY23vEJRnR3fTmKJWJcujWcq6ZAEO2ja8Lg4VAwKBPijQ3t8QBoywgnmJte9lS5xw881dfkCRuBX8q16dsPBV9I0xyRtREzr0vtTPTPoXJRCaXTRVwaAnpq9L0idNfVpsbitvGmB17NnO0pWzUpuk5jpVMdDGMvXXa+ixbFZr1ivnIq5y0YBaIwKO9jsPAm6aREUpL5ZsOooekTpiXVbs2he18voiqqIAh8=
  # DATABASE_URL
  - secure: bFgK63DoYGifwyv9IK4xAHYx8qkmcvnOU/DpmdhYufH5PB/2Fqpb8xbfb+AFiWGGzqDxC/iLyZg4zdsNlTZtXk7DKcC9PQBAjoJteSDFtco+jrgHt73IJxn8l/LM4MKUYf4AqGIcyVRPTeCeiDtdk+Qp2r2oQ83r+kIpzzboQqMtyfX+5R2NAwsDSDkfNVYqfOBA4vqOvZlblFTJpd8TCwBMKbEWruSxXMCZHXzUGX5zl+EpcU7pQs6+dCUjhO+tTWxv03NlZqDcQN672ZguH2NkbTPhIrZ4l99z4txfjTusIzvOC/bt6iwjgeHqaztQ2uVgnnxMXNFxiVV7/RtRL1f93UOeYy3tHg6mXSx9UHNbBx6evOsiEwtFYhJL+mRU/cvX8k2iNFG6nTGgvdoiVcsVkNvduDqGHK3MG+viaqJ6KD47Y4tYfWq6Yq9TVa0wrvYL6Ey/YVnV6VH7AApnXKhIBeLrhdTIFXTNwM533H8VL+y/wLVhx/Wi4q+VKMXy9AZ2JMvebSoDaUutdanx+qOFYsLOKZMDxWQmKSsAXM4rl0VE1eUd+3FfBMl7UW1zhz+B0yxwOu9Tm5+KQhqwsY8SxjCZNG2SRGF13gYCCRSvBgy0SB1bpBe4FWrb6d3VCSTDpzLZj/P4d2pDR1u31ZjyQ3jPtTrF8fYJqnT3r6E=
  # HEROKU_API_TOKEN
  - secure: Xb8yDS6nfC2y5fnHwXZQA62Q0+h2+awWKtBANSDCIWMNz/Al/RGXpY1+KX3WaV4B55HJKC4jRy3FgjV7ydAtaqt5vpzYJJOXsSaxps6P2mlOL3J5+9CcF+nv23Rl7Gsb9MmwT7ddo2uy1Jn2Zms9+TmnLnjUbqYFAv+Igkv95e6DzcqO1ExcSwbxTYorEK7vAu5YKl6dFonpBni0ITGbduNAZMr6pLGcc0yx2EeRzthzlxPD2ml/X3JUcLDzRb4mMONuqR7pKAEKj2pPzWwFSHUQXxOxCuWaPkiM3WOovz26rK+hUe1ltWvf7KX+Ufy5bJfKvLaOt4gaqz/qhvq0rFBZPHGhAc//+Ffm4GFD/r3RGUY1q8fC9vMc6Z7qJS6PP7J/Teurh/pH5goz1PNdck/Sfm8ADvRcLBpZ/FP7mLWzFyGp7Kp+c2LklrVUFjs1uNAbkFtqr9iHcowbpDxcECtzj8OZEt9XADx/v4T/j8Gr+PbWV31+J4d4v89ZrkHalSMIQuBLcU6g9IcQZpUzhpIK1Ziv91H+W79Q5wH1EBQ2Os3Y16mhPBPwp6ZA6fLN9sSCX52ZzPh+pu3yoaw4qwPrRgDvyWR93+wb6rATgUxPuU9MLyR/2biT8ToHojIbMWCgS+zqx0RNGNrUJWAE/ieaye/daMgHdNIhEvvMVaI=

deploy:
  provider: heroku
  api_key:
    secure: f1+vetyOoJyqq4SbN2UFO/DZ9N6srCWYmHX0AC8RgislwefSWzBwKGBLF0ZuYko16eUKbGj2JHh7G91hPnTeVU+bkNPe2EZ4kO2yH5JiLvUVR2XbK6RtN22GHdtSPzKy+YVdMvJ6mG8s4dnTGwl/GYhdTgrZ6bl6kANhT2hZk5n9SvDVJQ+TPotJn8ZyPVnf51//Dhn2acOu6DGV6NuUMQ8pgqlNaQ7UDVc8UzaoxuE6onOQxWrGxksuk/3eWD5vLs+7h+ALGJfPuOSKWoEs41Lw8PtWvsM7vL6ZmXNEXYWbtAjnXBpZWPF5C2F5TE+UJOKPJZID78gaeOkO615KuiC6gLPzLCagiz7h7tcyXqt99YgY84ugH9HqzJUG/3BM88jhCJuqpnp5ykzcWJVCO+0SdCNnZY/OguX2Z6pVDTntq8CIZ5seKGHQT1jHRu19MMCeei8G75mh7Xeq/g4xcGncAsbkMCOtnJ+8VC8uTe7Tvf/Joz+/T7tIaKglBD3P5tZwZX3iF915giN+4JghLcQ6NzrIFL+sbRN76b8XllSaYgK3qSbit7Lh/QjozZBZTjju8gWC2Hn++TDFZwuQPvKRLRAPW0kzdjLhWdDcHomyj4Lb1irQM7jVGMg9C6R/XhAniijWITGzKo4gFC9J5w2zvlNJqyd2HF75ooc/qgM=
  app:
    master: salume-prod
    staging: salume-staging
