language: java

jdk: oraclejdk8

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    chmod 755 ./update-gh-pages.sh
    ./update-gh-pages.sh
  fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then
    chmod 755 ./trigger-rainbow.sh
    ./trigger-rainbow.sh
  fi

env:
  global:
  - secure: AanbVsRGmMQnNolKxIL9p2zHLo59fXcrmRhZG+T1neTBJjlclQSwfwcdNTooNZQaxuJlTaRxWi7J8eTKQnpdjMnun9o1l9K/1NLOxBjlR7/9579p4tV4SLfKcR4OWUDJAs1vv8pXd9CmQpp8ihekXL9yR4Fo8pTbwj6CjnI9J9/5bFrBecU2oxm309qTzGaSofjiO9qEtzNW47ZDtexrpF8DM44rCo05OdysoPav1pVh2s/j9xMXWGKDO8RxkPSTr70rtX7W2OR6JZkz1PaEWrCj1n8SVVoe/Qn946y784BQ7WdlBZDDvwFezqBrLiXhAuuWh0GUI+varRn6MuRbUeujiMhgKkYWPI7GWyPLcgk7xy5hNU3yAy7UTDdnyrXw63l+ClfMuW4TzYU36Mz3DaVVxrNTjX35OBM0j1ZzFTeDJzt3AyfTgicw11IAIi5C/9T1PY4MjShvgC15UDmdZmtHLwJf6Q6OQot4/AcNZffW+/FjDxZ3kap7x1pZe+WhUVvALwEdd5FKLmeql8vydtWeuZKEQromqPR2Y8XcV7fYg4Q+1qwos+pfL9YKDOqamZXu/YIMmiduxFrQMiQhGx2qQFM2AP06QSEc94zhPrEoFoeqetMCSqRm4VEF3R23QGOE2V3H6NZEWgdFRuJduDGNpQvaghxQMYVLIyk1RuI=

deploy:
  provider: heroku
  api_key:
    secure: zxS4+O/SeOogoW1qQpUHAuAE+Wb1ZHznyHeYn0vqvj0CUYsw/y4jKw+beGU51WmYjHRrQpFU+/+MghMcPotzfBMzwX9ASjQ/I64T4yGrrUcoiM/AjKnti8OfBZQbP1bN5R8CcNKMYpnqqRu5P490LEOPz2QTAiCPQJexss9Hkzb60x6n4IXFjxhTsmuPy5J6DG2L1llcxLF//KIeNssi6mFHIyPRAzswjNMpZgr5bQsAZIX3M9MOHczX+PjNtsFz7iCQnp+NCwz5HQpzCeww6G7B2zmCwqFyHyJKuH9JSwTqGC4z5jsHA3Z/mbJhU+hLYi1VLHNi+ZhW80cF94s8amJDRm/+9FfQUwT5YmOLRCWhdFA8FrQnQLi9nJ16ZFu5MuM+mMCrvcjcxkAoKOQauHMdAw8ZcNiUrg1Go+y2j79Moau43OAWxBF1z8uoSe2NZizF4wVN4IUv1sSReEI48fN3iDzyZm8gkUnhzSuG1lESjvsQbPl6cKF8W2otl3EGHtKpJzlwxwyzIMF3QpIbgHQXO7cFTYVSykCbLkkXXdW0ZOFU/4NY0ls4TWuQ/45VkCIuX9m9exJgLJJqAgveW8LvIP8hxKgXcqWg6/Vao0xAoYzOnVgQe6DgtmOQ3e64nfpmZ67AwYQEZqtxYiXa03j9YXnqJUf7wcawzWkNtQM=
  app:
    master: frozen-mountain-3180
    staging: sheltered-river-1312

dd:
  secure: pO2ISNqHJ6HO3f753zcHYvczs6KUwJY7iTSZrXtKtqW9ner6dCjeyE8qsGXLy065gou9aHE6/kxcVe1GIrwbnOWzkTL+F90nKmLjZ2K0t8ur+3+Lo/9GkZ5/rYXrzd6vb4aKZFsdzAXo8cW9kUE9Gi25ZsgYI1I0QeIB89NH74lEk0g72kdsNIyPRduesh37XZ4DEBDKHYzj2EAHkyK69m2iGRcGPmDRj5B/fbHYQCBgrE+VgKDpUyaGzCDYgxLBTJebJ0i/kzXeyeaEOfR3Xe7DHe5vfOVgB3XTqejYVJl9DVGAlMdQ30OMJ0s0+JCVH602Tc7BWpQg5bRvVV3ekviXxTON60SPD6McT6ykalfZVPszNlYs+ls3pPoRmPC6c9a3T4lw5LX4dZNzIsPGisBQXYkCB+WU9llWoz7FHHewgyOCsvcs9FFpGA0YBTZGx2ij6EDR1mcwjgD9C/Cej+y6u2QuHoQam0LJQnI9JRGy7HaiTvUaHlV21016ofHFdDpXTkEhqazClUpGHa6MnNlVk7UFbNjhU3+bqsIBUJU7nQr8szlNNWpUx7IPDdczlrvtbBa5DZe0ZjMvXU98WLxKnWqIbnjhSy+KwgXIN/pq1v6ikqmFZGrULUvLrfdU8u9v9H9MeF+bpR6nAKTldieyKKOxoOk3sq2jU0q/yus=
