ALTER TABLE salumistore.variety ALTER COLUMN image_link TYPE varchar(150);

INSERT INTO salumistore.variety VALUES (11, 'Bresaola'                 , NULL);
INSERT INTO salumistore.variety VALUES (12, 'Bresaola della Valtellina', 'c/cb/Bresaola-Valt-IGP.jpg');
INSERT INTO salumistore.variety VALUES (13, 'Salame di turgia'         , 'a/aa/2012_01_28_salame_turgia.jpg/260px-2012_01_28_salame_turgia.jpg');
INSERT INTO salumistore.variety VALUES (14, 'Carne salada del Trentino', 'thumb/5/50/Carne_Salada_e_fasoi.JPG/260px-Carne_Salada_e_fasoi.JPG');
INSERT INTO salumistore.variety VALUES (15, 'Borzat'                   , NULL);
INSERT INTO salumistore.variety VALUES (16, 'Coppa di testa'           , 'thumb/d/da/Coppa_di_testa%2C_black_mission_figs%2C_pea_tendrils%2C_saba.jpg/260px-Coppa_di_testa%2C_black_mission_figs%2C_pea_tendrils%2C_saba.jpg');
INSERT INTO salumistore.variety VALUES (17, 'Coppa (salume)'           , 'thumb/2/2b/Sweetcapicola.JPG/260px-Sweetcapicola.JPG');
INSERT INTO salumistore.variety VALUES (18, 'Mortadella di Campotosto' , 'thumb/b/bd/Mortadella_di_Campotosto.jpg/220px-Mortadella_di_Campotosto.jpg');
INSERT INTO salumistore.variety VALUES (19, 'Ciuiga'                   , NULL);
INSERT INTO salumistore.variety VALUES (20, 'Ciccioli'                 , 'thumb/5/54/Ciccioli.jpg/260px-Ciccioli.jpg');
INSERT INTO salumistore.variety VALUES (21, 'Cicciolata'               , NULL);
INSERT INTO salumistore.variety VALUES (22, 'Ciauscolo'                , NULL);
INSERT INTO salumistore.variety VALUES (23, 'Cervellatine'             , NULL);
INSERT INTO salumistore.variety VALUES (24, 'Cervellata'               , NULL);
INSERT INTO salumistore.variety VALUES (25, 'Bardiccio'                , 'thumb/f/fc/Bardiccio.jpeg/260px-Bardiccio.jpeg');
INSERT INTO salumistore.variety VALUES (26, 'Annoia'                   , NULL);
INSERT INTO salumistore.variety VALUES (27, 'Salsiccia di Bra'         , 'thumb/0/02/Salsiccia_di_bra.jpg/260px-Salsiccia_di_bra.jpg');
INSERT INTO salumistore.variety VALUES (28, 'Teteun'                   , 'thumb/c/cf/Teteun_affettato.png/260px-Teteun_affettato.png');

INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Bresaola'                  , 29.55, 31.00, 2, 11);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Bresaola della Valtellina' , 29.65, 29.00, 2, 12);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Salame di turgia'          , 34.55, 31.00, 2, 13);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Carne salada del Trentino' , 29.00, 31.00, 2, 14);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Borzat'                    , 34.00, 35.00, 2, 15);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Coppa di testa'            , 34.00, 40.00, 2, 16);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Coppa'                     , 45.00, 37.00, 2, 17);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Mortadella di Campotosto'  , 16.00, 42.00, 2, 18);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Ciuiga'                    , 57.00, 32.00, 2, 19);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Ciccioli'                  , 57.00, 34.00, 2, 20);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Cicciolata'                , 59.00, 33.00, 2, 21);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Ciauscolo'                 , 58.00, 37.00, 2, 22);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Cervellatine'              , 42.00, 38.00, 2, 23);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Cervellata'                , 22.90, 38.00, 2, 24);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Bardiccio'                 , 19.99, 37.00, 2, 25);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Annoia'                    , 21.99, 39.00, 2, 26);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Salsiccia di Bra'          , 22.99, 44.00, 2, 27);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Teteun'                    , 23.99, 41.00, 2, 28);