UPDATE salumistore.variety SET image_link = 'thumb/a/aa/2012_01_28_salame_turgia.jpg/260px-2012_01_28_salame_turgia.jpg' WHERE id = 13;

INSERT INTO salumistore.variety VALUES (29, 'Cotechino'                 , 'thumb/0/0c/Cotechino-Servito-Polenta-Lenticchie.jpg/800px-Cotechino-Servito-Polenta-Lenticchie.jpg');
INSERT INTO salumistore.variety VALUES (30, 'Culatello di Zibello'      , 'c/c7/Culatello_di_Zibello_%26_burrata.jpg');
INSERT INTO salumistore.variety VALUES (31, 'Figatelli'                 , 'thumb/3/3b/Corse_figatelle_05159.jpg/225px-Corse_figatelle_05159.jpg');
INSERT INTO salumistore.variety VALUES (32, 'Finocchiona'               , 'thumb/f/ff/Finocchiona_gigante.jpg/800px-Finocchiona_gigante.jpg');
INSERT INTO salumistore.variety VALUES (33, 'Guanciale di maiale'       , 'thumb/f/ff/Guanciale_di_Norcia.jpg/330px-Guanciale_di_Norcia.jpg');
INSERT INTO salumistore.variety VALUES (34, 'Lardo'                     , 'f/fa/Lardo_di_Colonnata.JPG');
INSERT INTO salumistore.variety VALUES (35, 'Luganega'                  , 'thumb/6/60/Luganega.jpg/260px-Luganega.jpg');
INSERT INTO salumistore.variety VALUES (36, 'Luganeghe della Val Leogra', NULL);
INSERT INTO salumistore.variety VALUES (37, 'Mariola (salume)'          , NULL);
INSERT INTO salumistore.variety VALUES (38, 'Mazzafegato'               , NULL);
INSERT INTO salumistore.variety VALUES (39, 'Mortadella Bologna'        , 'thumb/b/be/Mortadella.jpg/260px-Mortadella.jpg');
INSERT INTO salumistore.variety VALUES (40, 'Mortadella di Prato'       , NULL);
INSERT INTO salumistore.variety VALUES (41, 'Mortadella di fegato'      , 'thumb/4/4c/Mortadella_orta_affettata.jpg/220px-Mortadella_orta_affettata.jpg');
INSERT INTO salumistore.variety VALUES (42, 'Mortandela'                , NULL);
INSERT INTO salumistore.variety VALUES (43, 'Pancetta'                  , 'thumb/0/09/Pancetta_affumicata.JPG/220px-Pancetta_affumicata.JPG');
INSERT INTO salumistore.variety VALUES (44, 'Bacon (salume)'            , 'thumb/3/3f/Flickr_bokchoi-snowpea_4266923676--Roast_peameal_bacon.jpg/220px-Flickr_bokchoi-snowpea_4266923676--Roast_peameal_bacon.jpg');
INSERT INTO salumistore.variety VALUES (45, 'Porchetta'                 , 'thumb/5/52/Porchetta_-_Provincia_di_Roma.jpg/180px-Porchetta_-_Provincia_di_Roma.jpg');
INSERT INTO salumistore.variety VALUES (46, 'Porchetta di Ariccia'      , 'thumb/3/3b/Panino_con_porchetta_di_Arricia.jpg/260px-Panino_con_porchetta_di_Arricia.jpg');
INSERT INTO salumistore.variety VALUES (47, 'Pastin'                    , NULL);

INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Cotechino'                 , 34.99, 45.00, 2, 29);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Culatello di Zibello'      , 36.99, 46.00, 2, 30);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Figatelli'                 , 24.99, 39.00, 2, 31);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Finocchiona'               , 47.99, 77.00, 2, 32);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Guanciale di maiale'       , 37.99, 66.00, 2, 33);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Lardo'                     , 56.99, 43.00, 2, 34);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Luganega'                  , 27.99, 36.00, 2, 35);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Luganeghe della Val Leogra', 36.99, 34.00, 2, 36);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Mariola'                   , 36.99, 35.00, 2, 37);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Mazzafegato'               , 36.99, 36.00, 2, 38);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Mortadella Bologna'        , 37.99, 43.00, 2, 39);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Mortadella di Prato'       , 29.99, 47.00, 2, 40);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Mortadella di Fegato'      , 34.99, 33.00, 2, 41);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Mortandela'                , 33.99, 42.00, 2, 42);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Pancetta'                  , 34.99, 41.00, 2, 43);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Bacon'                     , 37.99, 38.00, 2, 44);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Porchetta'                 , 37.99, 56.00, 2, 45);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Porchetta di Ariccia'      , 38.99, 67.00, 2, 46);
INSERT INTO salumistore.products (name, price, fat, reputation, variety) VALUES ('Pastin'                    , 38.99, 37.00, 2, 47);
